---
abstract: 'Emnulate Class::Accessor::Fast using attributes'
author:
  - 'Guillermo Roditi (groditi) <groditi@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Emulate-Class-Accessor-Fast
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.31
resources:
  license: http://dev.perl.org/licenses/
version: 0.00500
